# Generated by Django 5.2.5 on 2026-03-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Church Committee'), ('leader', 'Church Leader (Pastor)')], default='admin', max_length=20),
        ),
    ]
