# Generated by Django 5.2.5 on 2026-03-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='t_user_role',
        ),
    ]
